[package]
name = "world_data"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui = { path = "../ui" }
input = { path = "../input" }
others = { path = "../others" }
ecs = { path = "../ecs" }
rendering = { path = "../rendering" }
assets = { path = "../assets" }
debug = { path = "../debug" }
veclib = { git = "https://github.com/jedjoud10/veclib" }