[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
lazy_static = "1.4.0"
slotmap = "1.0.6"
bitfield = { git = "https://github.com/jedjoud10/bitfield" }
parking_lot = "0.12.0"
others = { path = "../others" }
ecs-derive = { path = "./ecs-derive"  }
getset = "0.1.2"
enum-as-inner = "0.3.3"