[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rendering = { path = "../rendering" }
assets = { path = "../assets" }
math = { path = "../math" }
gl = "0.14.0"
egui = "0.16.1"
egui-winit = "0.16.0"