[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rendering = { path = "../rendering" }
assets = { path = "../assets" }
math = { path = "../math" }
egui = "0.17.0"
vek = "0.15.6"
egui-winit = "0.17.0"
parking_lot = "0.12.0"
