[package]
name = "hypothermia"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[workspace]

members = [
    "crates\\hypo_dev_game",
    "crates\\hypo_main",
    "crates\\hypo_system_event_data",
    "crates\\hypo_errors",
    "crates\\hypo_debug",
    "crates\\hypo_core",
    "crates\\hypo_systems",
    "crates\\hypo_ecs",
    "crates\\hypo_math",
    "crates\\hypo_rendering",
    "crates\\hypo_input",
    "crates\\hypo_defaults",
    "crates\\hypo_others",
    "crates\\hypo_resources",
    "crates\\hypo_resources_packer",
    "crates\\hypo_terrain",
    "crates\\hypo_ui"
]


