[package]
name = "cflake-engine"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "crates/app" }

[workspace]
members = [
    "crates/assets",
    "crates/audio",    
    "crates/ecs",    
    "crates/app",
    "crates/gui",
    "crates/input",
    "crates/math",
    "crates/network",
    "crates/physics",
    "crates/rendering",
    "crates/terrain",
    "crates/opengl",
    "crates/world",
]

[profile.dev]
opt-level = 3