[package]
name = "hypothermia"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "crates\\dev_game",
    "crates\\main",
    "crates\\system_event_data",
    "crates\\errors",
    "crates\\debug",
    "crates\\core",
    "crates\\systems",
    "crates\\ecs",
    "crates\\math",
    "crates\\rendering",
    "crates\\input",
    "crates\\defaults",
    "crates\\others",
    "crates\\resources",
    "crates\\resources_packer",
    "crates\\terrain",
    "crates\\ui",
    "crates\\io",
    "crates\\fonts",
    "crates\\font_packer"
]


