[package]
name = "cflake-engine"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "engine"
path = "src/lib.rs"

[[bin]]
name = "dev_game"
path = "src/bin.rs"

[dependencies]
window = { path = "crates\\window" }

[workspace]
members = [
    "crates\\assets",
    "crates\\core",
    "crates\\debug",
    "crates\\defaults",
    "crates\\ecs",
    "crates\\window",
    "crates\\font_generator",
    "crates\\fonts",
    "crates\\input",
    "crates\\io",
    "crates\\main",
    "crates\\math",
    "crates\\network",
    "crates\\others",
    "crates\\physics",
    "crates\\rendering",
    "crates\\terrain",
    "crates\\terrain_interpreter",
    "crates\\ui",
    "crates\\worker_threads"
]


