[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean-publish]
command = "cargo"
args = ["clean", "--release"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-publish]
command = "cargo"
args = ["build", "--release"]

[tasks.run]
command = "cargo"
args = ["run", "--release"]

[tasks.debug]
command = "cargo"
args = ["run"]

[tasks.fix-certificate]
command = "./fix-certificate.bat"

[tasks.publish-cert]
dependencies = [
    "clean-publish",
    "run",
    "fix-certificate"
]