[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean-publish]
command = "cargo"
args = ["clean", "--release"]

[tasks.run-release]
command = "cargo"
args = ["run", "--release"]

[tasks.fix-certificate]
command = "./fix-certificate.bat"

[tasks.publish-cert]
dependencies = [
    "clean-publish",
    "run-release",
    "fix-certificate"
]