[package]
name = "input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.28.0"
multimap = "0.8.3"
veclib = { git = "https://github.com/jedjoud10/veclib" }
ahash = "0.7.6"