[package]
name = "ui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
others = { path = "../others" }
fonts = { path = "../fonts" }
resources = { path = "../resources" }
