[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
bytemuck = "1.12.3"
parking_lot = "0.12.0"
ash = "0.37.0+1.3.209"
raw-window-handle = "0.5.0"
ash-window = "0.12.0"
gpu-allocator = { version = "0.21.0", features = ["vulkan"] }
log = { workspace = true }