[package]
name = "dev_game"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
main = { path = "../main" }

[build-dependencies]
resources_packer = { path = "../resources_packer" }