[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
ordered_vec = { git = "https://github.com/jedjoud10/ordered_vec" }
bitfield = { git = "https://github.com/jedjoud10/bitfield" }
assets = { path = "../assets" }
math = { path = "../math" }
others = { path = "../others" }
egui_glfw_gl = "0.13.1"
lazy_static = "1.4.0"
arrayvec = "0.7.2"
smallvec = "1.8.0"
bitflags = "1.3.2"
enum-as-inner = "0.3.3"
glfw = "0.41.0"
ahash = "0.7.6"
gl = "0.14.0"
image = "0.23.14"