[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
opengl = { path = "../opengl" }
world = { path = "../world" }
ecs = { path = "../ecs" }
mikktspace = "0.3.0"
getset = "0.1.2"
snailquote = "0.3.1"
vek = "0.15.6"
slotmap = "1.0.6"
half = "1.8.2"
hdrldr = "0.1.2"
assets = { path = "../assets" }
time = { path = "../time" }
rayon = "1.5.1"
math = { path = "../math" }
lazy_static = "1.4.0"
arrayvec = "0.7.2"
smallvec = "1.8.0"
itertools = "0.10.3"
bitflags = "1.3.2"
seq-macro = "0.3.0"
enum-as-inner = "0.4.0"
glutin = "0.28.0"
ahash = "0.7.6"
parking_lot = "0.12.0"
obj-rs = "0.7.0"
image = "0.24.1"
num = "0.4.0"
paste = "1.0.7"
nohash-hasher = "0.2.0"