[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
bitfield = { git = "https://github.com/jedjoud10/bitfield" }
slotmap = "1.0.6"
getset = "0.1.2"
assets = { path = "../assets" }
math = { path = "../math" }
others = { path = "../others" }
lazy_static = "1.4.0"
arrayvec = "0.7.2"
smallvec = "1.8.0"
bitflags = "1.3.2"
enum-as-inner = "0.3.3"
glutin = "0.28.0"
ahash = "0.7.6"
gl = "0.14.0"
parking_lot = "0.12.0"
obj-rs = "0.7"
image = "0.23.14"