[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
utils = { path = "../utils" }
math = { path = "../math" }
ecs = { path = "../ecs" }
graphics = { path = "../graphics" }
assets = { path = "../assets" }
rendering-derive = { path = "./rendering-derive"  }
paste = "1.0.7"
arrayvec = "0.7.2"
mikktspace = "0.3.0"
bitflags = "1.3.2"
obj-rs = "0.7.0"
log = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }

[features]
double-precision = ["ecs/double-precision"]
two-dim = ["ecs/two-dim"]