[package]
name = "rendering"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
assets = { path = "../assets" }
ecs = { path = "../ecs" }
others = { path = "../others" }
bitflags = "1.3.2"
lazy_static = "1.4.0"
glfw = "0.41.0"
gl = "0.14.0"
image = "0.23.14"