[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
ecs = { path = "../ecs" }
graphics = { path = "../graphics" }
assets = { path = "../assets" }

log = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true }
parking_lot = { workspace = true }

[features]
two-dim = []