[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
ecs = { path = "../ecs" }
assets = { path = "../assets" }
time = { path = "../time" }
math = { path = "../math" }
winit = "0.27.5"
nohash-hasher = "0.2.0"
raw-window-handle = "0.5.0"
ash-window = "0.12.0"
ash = "0.37.0+1.3.209"

[features]
two-dim = ["ecs/two-dim"]