[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
assets = { path = "../assets" }
math = { path = "../math" }
utils = { path = "../utils" }

# Vulkan bindings and Window creation
ash = "0.37.1"
raw-window-handle = "0.5.0"
ash-window = "0.12.0"

# Utils and helpers
smallvec = "1.10.0"
gpu-allocator = { version = "0.21.0", features = ["vulkan"] }
gpu-descriptor = "0.2.3"
thread_local = "1.1.4"
nohash-hasher = "0.2.0"
dashmap = "5.4.0"
shaderc = "0.8.1"

bitflags = "1.3.2"
winit = "0.27.5"
bytemuck = "1.12.3"
snailquote = "0.3.1"
half = { version = "2.1.0", features = ["bytemuck"] }
paste = "1.0.7"
image = "0.24.5"
once_cell = "1.17.0"
spirv-reflect = "0.2.3"
log = { workspace = true }
thiserror = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true, features = ["bytemuck"] }
parking_lot = { workspace = true }
lazy_static = { workspace = true }

[features]
headless = []