[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
assets = { path = "../assets" }
math = { path = "../math" }
utils = { path = "../utils" }
vulkan = { path = "../vulkan" }

winit = "0.27.5"
bytemuck = "1.12.3"
log = { workspace = true }
thiserror = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true }
parking_lot = { workspace = true }

[features]
headless = []