[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
assets = { path = "../assets" }
math = { path = "../math" }
utils = { path = "../utils" }

# Vulkan bindings and Window creation
ash = "0.37.1"
raw-window-handle = "0.5.0"
ash-window = "0.12.0"
winit = "0.27.5"

# Utils and helpers
bytemuck = "1.12.3"
smallvec = "1.10.0"
gpu-allocator = { version = "0.21.0", features = ["vulkan"] }
thread_local = "1.1.4"
nohash-hasher = "0.2.0"
bitflags = "1.3.2"


log = { workspace = true }
thiserror = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true }
parking_lot = { workspace = true }

[features]
headless = []