[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
assets = { path = "../assets" }
math = { path = "../math" }
utils = { path = "../utils" }
nohash-hasher = "0.2.0"
parking_lot = "0.12.0"
raw-window-handle = "0.5.0"
vulkano = "0.32.1"
winit = "0.27.5"
bytemuck = "1.12.3"
vulkano-win = "0.32.0"
vulkano-shaders = "0.32.0"


log = { workspace = true }
thiserror = { workspace = true }
ahash = { workspace = true } 
vek = { workspace = true }

[features]
headless = []