[package]
name = "rendering-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = "1.0.88"
quote = "1.0.15"
proc-macro2 = "1.0.49"
proc-macro-crate = "1.2.1"

[lib]
proc-macro = true
