[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
num-traits = "0.2.15"
itertools = "0.10.3"
atomic-traits = "0.3.0"
world = { path = "../world" }
slotmap = "1.0.6"
rayon = "1.8.0"
chrono = "0.4.23"
dirs = "5.0.1"
parking_lot = { workspace = true }
log = { workspace = true }

[features]
extended-tuples = []