[package]
name = "systems"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecs = { path = "../ecs" }
errors = { path = "../errors" }
others = { path = "../others" }
world_data = { path = "../world_data" }