[package]
name = "defaults"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
core = { path = "../core" }
ui = { path = "../ui" }
physics = { path = "../physics" }
math = { path = "../math" }
fonts = { path = "../fonts"  }
ecs = { path = "../ecs" }
assets = { path = "../assets" }
rendering = { path = "../rendering" }
terrain = { path = "../terrain" }
debug = { path = "../debug" }
input = { path = "../input" }
others = { path = "../others" }