[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.15.6"
ahash = "0.7.6"
math = { path = "../math" }
rendering = { path = "../rendering" }
slotmap = "1.0.6"
half = "1.8.2"
threadpool = "1.8.1"
rayon = "1.5.1"
parking_lot = "0.12.0"
