[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
utils = { path = "../utils" }
math = { path = "../math" }
ecs = { path = "../ecs" }
graphics = { path = "../graphics" }
assets = { path = "../assets" }