[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
rayon = "1.5.1"
half = "1.8.2"
math = { path = "../math" }
ui = { path = "../ui" }
ecs = { path = "../ecs" }
rendering = { path = "../rendering" }
assets = { path = "../assets" }
others = { path = "../others" }
input = { path = "../input" }
debug = { path = "../debug" }