[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world = { path = "../world" }
utils = { path = "../utils" }
math = { path = "../math" }
ecs = { path = "../ecs" }
coords = { path = "../coords" }
graphics = { path = "../graphics" }
rendering = { path = "../rendering" }
assets = { path = "../assets" }
rand = "0.8.5"
rayon = "1.7.0"
itertools = "0.10.5"
vek = { workspace = true }
log = { workspace = true }
ahash = { workspace = true } 
thiserror = { workspace = true }