[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veclib = { git = "https://github.com/jedjoud10/veclib" }
log = { version = "0.4.14", features = ["std"] }
ahash = "0.7.6"
math = { path = "../math" }
rendering = { path = "../rendering" }
half = "1.8.2"