[package]
name = "world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
ahash = "0.7.6"
glutin = "0.28.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
getset = "0.1.2"
vek = "0.15.6"
serde = { version = "1.0.136", features = ["derive"] }
input = { path = "../input" }
physics = { path = "../physics" }
network = { path = "../network" }
others = { path = "../others" }
resources = { path = "../resources" }
ecs = { path = "../ecs" }
rendering = { path = "../rendering" }
assets = { path = "../assets" }
math = { path = "../math" }
gui = { path = "../gui" }
io = { path = "../io" }
terrain = { path = "../terrain" }
audio = { path = "../audio" }
