[package]
name = "world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.6"
parking_lot = "0.12.0"
glutin = "0.28.0"
ahash = "0.7.6"
num_cpus = "1.13.1"
seq-macro = "0.3.0"
paste = "1.0.7"
casey = "0.3.3"
arrayvec = "0.7.2"
math = { path = "../math" }