[package]
name = "world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.6"
winit = "0.28.0"
num_cpus = "1.13.1"
seq-macro = "0.3.0"
paste = "1.0.7"
casey = "0.3.3"
lazy_static = "1.4.0"
pretty-type-name = "1.0.1"
arrayvec = "0.7.2"
log_err = "1.1.1"
math = { path = "../math" }

ahash = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[features]
debug-names = []