[package]
name = "io"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
platform-dirs = "0.3.0"
errors = { path = "../errors" }