[package]
name = "math"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
veclib = { git = "https://github.com/jedjoud10/veclib" }
ordered_vec = { git = "https://github.com/jedjoud10/ordered_vec" }
others = { path = "../others" }
rayon = "1.5"