name: Rust

on:
  push:
    branches: [ main, dev, proto, vulkan-renderer ]
  pull_request:
    branches: [ main, dev, proto, vulkan-renderer ]

env:
  CARGO_TERM_COLOR: always



jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --`
